# Generated by Django 5.1.15 on 2026-07-16 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('class_sessions', '0001_initial'),
        ('payroll', '0001_initial'),
        ('people', '0003_auditlog'),
        ('timetable', '0002_alter_class_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='payslip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='payroll.payslip'),
        ),
        migrations.AddField(
            model_name='session',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='people.teacher'),
        ),
        migrations.AddField(
            model_name='session',
            name='timetable_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='timetable.timetableslot'),
        ),
        migrations.AddField(
            model_name='sessionattendance',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='class_sessions.session'),
        ),
        migrations.AddField(
            model_name='sessionattendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='people.student'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['teacher'], name='class_sessi_teacher_ff8c6d_idx'),
        ),
        migrations.AddConstraint(
            model_name='session',
            constraint=models.UniqueConstraint(fields=('timetable_slot', 'start_time'), name='unique_session_per_slot_start'),
        ),
        migrations.AddConstraint(
            model_name='sessionattendance',
            constraint=models.UniqueConstraint(fields=('session', 'student'), name='unique_attendance_per_session_student'),
        ),
    ]
