# Generated by Django 5.1.15 on 2026-07-16 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('class_sessions', '0002_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='session',
            name='unique_session_per_slot_start',
        ),
    ]
