# Generated by Django 5.1.15 on 2026-07-16 10:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_sessions', '0003_remove_session_unique_session_per_slot_start'),
        ('payroll', '0001_initial'),
        ('people', '0004_student_check_in_token_alter_user_role'),
        ('timetable', '0002_alter_class_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('check_in_type', models.CharField(choices=[('qr', 'QR Code'), ('manual', 'Manual')], default='qr', max_length=10)),
            ],
            options={
                'verbose_name': 'Check In',
                'verbose_name_plural': 'Check Ins',
                'db_table': 'check_ins',
            },
        ),
        migrations.AddConstraint(
            model_name='session',
            constraint=models.UniqueConstraint(fields=('timetable_slot', 'start_time'), name='unique_session_per_slot_start'),
        ),
        migrations.AddField(
            model_name='checkin',
            name='checked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='check_ins_performed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='checkin',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_ins', to='people.student'),
        ),
        migrations.AddIndex(
            model_name='checkin',
            index=models.Index(fields=['student', 'timestamp'], name='check_ins_student_8d1079_idx'),
        ),
    ]
