# Generated by Django 5.1.15 on 2026-07-16 12:11

import django.db.models.functions.datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_sessions', '0004_checkin_session_unique_session_per_slot_start_and_more'),
        ('people', '0004_student_check_in_token_alter_user_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='checkin',
            constraint=models.UniqueConstraint(django.db.models.functions.datetime.TruncDate('timestamp'), models.F('student'), name='unique_student_daily_checkin'),
        ),
    ]
