# Generated by Django 5.1.15 on 2026-07-16 12:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_sessions', '0005_checkin_unique_student_daily_checkin'),
        ('people', '0004_student_check_in_token_alter_user_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='checkin',
            name='unique_student_daily_checkin',
        ),
        migrations.AddField(
            model_name='checkin',
            name='date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddConstraint(
            model_name='checkin',
            constraint=models.UniqueConstraint(fields=('student', 'date'), name='unique_student_daily_checkin'),
        ),
    ]
