# Generated by Django 5.1.15 on 2026-07-16 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_sessions', '0006_remove_checkin_unique_student_daily_checkin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='date',
            field=models.DateField(auto_now_add=True, db_index=True),
        ),
    ]
