# Generated by Django 5.1.15 on 2026-07-17 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_sessions', '0008_alter_checkin_date'),
        ('people', '0005_alter_student_check_in_token_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='sessionattendance',
            index=models.Index(fields=['student'], name='class_sessi_student_90884c_idx'),
        ),
        migrations.AddIndex(
            model_name='sessionattendance',
            index=models.Index(fields=['session', 'status'], name='class_sessi_session_7500cc_idx'),
        ),
    ]
