# Generated by Django 5.1.15 on 2026-07-17 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_sessions', '0009_sessionattendance_class_sessi_student_90884c_idx_and_more'),
        ('payroll', '0002_adjustment_payroll_adj_teacher_e88798_idx_and_more'),
        ('people', '0005_alter_student_check_in_token_and_more'),
        ('timetable', '0003_timetableslot_timetable_t_teacher_c24da5_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['teacher', 'start_time'], name='class_sessi_teacher_48b9d4_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['start_time'], name='class_sessi_start_t_524af1_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['status'], name='class_sessi_status_dcc8e7_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['paid'], name='class_sessi_paid_e18ca6_idx'),
        ),
    ]
