# Generated by Django 5.1.15 on 2026-07-17 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('class_sessions', '0010_session_class_sessi_teacher_48b9d4_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='session',
            name='class_sessi_teacher_ff8c6d_idx',
        ),
    ]
