# Generated by Django 5.1.15 on 2026-07-17 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('class_sessions', '0011_remove_session_class_sessi_teacher_ff8c6d_idx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='payslip',
        ),
    ]
