# Generated by Django 5.1.15 on 2026-07-21 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_sessions', '0012_remove_session_payslip'),
        ('people', '0007_alter_staff_contact_alter_student_contact_and_more'),
        ('timetable', '0004_alter_timetableslot_class_obj_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='class_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='timetable.class'),
        ),
        migrations.AlterField(
            model_name='session',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='people.teacher'),
        ),
        migrations.AlterField(
            model_name='session',
            name='timetable_slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='timetable.timetableslot'),
        ),
        migrations.CreateModel(
            name='AdHocSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='scheduled', max_length=20)),
                ('paid', models.BooleanField(default=False)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adhoc_sessions', to='people.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adhoc_sessions', to='people.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='AdHocSessionAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late')], default='absent', max_length=20)),
                ('ad_hoc_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='class_sessions.adhocsession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adhoc_attendances', to='people.student')),
            ],
        ),
        migrations.AddIndex(
            model_name='adhocsession',
            index=models.Index(fields=['teacher', 'date'], name='class_sessi_teacher_417b44_idx'),
        ),
        migrations.AddIndex(
            model_name='adhocsession',
            index=models.Index(fields=['status'], name='class_sessi_status_a503fd_idx'),
        ),
        migrations.AddIndex(
            model_name='adhocsession',
            index=models.Index(fields=['paid'], name='class_sessi_paid_1bec47_idx'),
        ),
        migrations.AddConstraint(
            model_name='adhocsession',
            constraint=models.UniqueConstraint(fields=('teacher', 'subject', 'date', 'start_time'), name='unique_adhoc_session_per_start'),
        ),
        migrations.AddIndex(
            model_name='adhocsessionattendance',
            index=models.Index(fields=['student'], name='class_sessi_student_9994b2_idx'),
        ),
        migrations.AddIndex(
            model_name='adhocsessionattendance',
            index=models.Index(fields=['ad_hoc_session', 'status'], name='class_sessi_ad_hoc__caed74_idx'),
        ),
        migrations.AddConstraint(
            model_name='adhocsessionattendance',
            constraint=models.UniqueConstraint(fields=('ad_hoc_session', 'student'), name='unique_attendance_per_adhoc_session_student'),
        ),
    ]
