# Generated by Django 5.1.15 on 2026-07-23 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_sessions', '0013_alter_session_class_obj_alter_session_teacher_and_more'),
        ('people', '0007_alter_staff_contact_alter_student_contact_and_more'),
        ('timetable', '0004_alter_timetableslot_class_obj_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='session',
            new_name='idx_session_teacher_start',
            old_name='class_sessi_teacher_48b9d4_idx',
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['class_obj', 'start_time'], name='idx_session_class_start'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['status', 'paid'], name='idx_session_status_paid'),
        ),
        migrations.AddIndex(
            model_name='sessionattendance',
            index=models.Index(fields=['session', 'student'], name='idx_attendance_sess_stud'),
        ),
    ]
