# Generated by Django 5.1.15 on 2026-08-05 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_sessions', '0014_rename_class_sessi_teacher_48b9d4_idx_idx_session_teacher_start_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adhocsessionattendance',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('excused', 'Excused')], default='absent', max_length=20),
        ),
        migrations.AlterField(
            model_name='sessionattendance',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('excused', 'Excused')], default='absent', max_length=20),
        ),
    ]
