# Generated by Django 5.1.15 on 2026-08-05 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('class_sessions', '0015_add_excused_attendance_status'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='adhocsession',
            name='class_sessi_paid_1bec47_idx',
        ),
        migrations.RemoveIndex(
            model_name='session',
            name='class_sessi_paid_e18ca6_idx',
        ),
        migrations.RemoveIndex(
            model_name='session',
            name='idx_session_status_paid',
        ),
        migrations.RemoveField(
            model_name='adhocsession',
            name='paid',
        ),
        migrations.RemoveField(
            model_name='session',
            name='paid',
        ),
    ]
