# Generated by Django 5.1.15 on 2026-08-05 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_sessions', '0016_remove_payroll_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='adhocsessionattendance',
            name='auto_marked_by_checkin',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auto_marked_adhoc_attendances', to='class_sessions.checkin'),
        ),
        migrations.AddField(
            model_name='sessionattendance',
            name='auto_marked_by_checkin',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auto_marked_session_attendances', to='class_sessions.checkin'),
        ),
    ]
