# Generated by Django 5.1.15 on 2026-08-06 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_sessions', '0017_attendance_auto_marked_by_checkin'),
        ('people', '0013_student_check_in_token_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='adhocsession',
            name='actual_teacher',
            field=models.ForeignKey(blank=True, help_text='Who actually taught. Null means taught as assigned. Set when a substitute covers.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='adhoc_sessions_taught', to='people.teacher'),
        ),
        migrations.AddField(
            model_name='session',
            name='actual_teacher',
            field=models.ForeignKey(blank=True, help_text='Who actually taught. Null means taught as assigned (or not yet run). Set when a substitute covers.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sessions_taught', to='people.teacher'),
        ),
    ]
