# Generated by Django 5.1.15 on 2026-07-16 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('class_sessions', '0001_initial'),
        ('people', '0003_auditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_count', models.IntegerField()),
                ('rate_applied', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gross_pay', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax_deduction', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('other_deductions', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('adjustments_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('net_pay', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('paid', 'Paid')], default='draft', max_length=20)),
                ('issued_date', models.DateField(auto_now_add=True)),
                ('pay_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to='payroll.payperiod')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to='people.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Adjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('applied', 'Applied')], default='pending', max_length=20)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjustments', to='class_sessions.session')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='people.teacher')),
                ('applied_payslip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjustments', to='payroll.payslip')),
            ],
        ),
    ]
