# Generated by Django 5.1.15 on 2026-07-17 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_sessions', '0009_sessionattendance_class_sessi_student_90884c_idx_and_more'),
        ('payroll', '0001_initial'),
        ('people', '0005_alter_student_check_in_token_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='adjustment',
            index=models.Index(fields=['teacher', 'status', 'applied_payslip'], name='payroll_adj_teacher_e88798_idx'),
        ),
        migrations.AddIndex(
            model_name='payperiod',
            index=models.Index(fields=['start_date', 'end_date'], name='payroll_pay_start_d_fd07d2_idx'),
        ),
    ]
