# Generated by Django 5.1.15 on 2026-07-17 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_adjustment_payroll_adj_teacher_e88798_idx_and_more'),
        ('people', '0005_alter_student_check_in_token_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='payslip',
            index=models.Index(fields=['teacher', 'pay_period'], name='payroll_pay_teacher_267d58_idx'),
        ),
        migrations.AddIndex(
            model_name='payslip',
            index=models.Index(fields=['status'], name='payroll_pay_status_409e9f_idx'),
        ),
    ]
