# Generated by Django 5.1.15 on 2026-07-17 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_payslip_payroll_pay_teacher_267d58_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payslip',
            name='pay_period',
        ),
        migrations.RemoveField(
            model_name='payslip',
            name='teacher',
        ),
        migrations.DeleteModel(
            name='Adjustment',
        ),
        migrations.DeleteModel(
            name='PayPeriod',
        ),
        migrations.DeleteModel(
            name='Payslip',
        ),
    ]
