# Generated by Django 5.1.15 on 2026-07-16 10:28

import secrets

from django.db import migrations, models


def populate_check_in_tokens(apps, schema_editor):
    Student = apps.get_model('people', 'Student')
    for student in Student.objects.filter(check_in_token=''):
        student.check_in_token = secrets.token_urlsafe(32)
        student.save(update_fields=['check_in_token'])


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_auditlog'),
    ]

    operations = [
        # 1. Add field without unique constraint first
        migrations.AddField(
            model_name='student',
            name='check_in_token',
            field=models.CharField(blank=True, editable=False, max_length=64, unique=False),
        ),
        # 2. Backfill tokens for existing students
        migrations.RunPython(populate_check_in_tokens, reverse_code=migrations.RunPython.noop),
        # 3. Alter to add the unique constraint
        migrations.AlterField(
            model_name='student',
            name='check_in_token',
            field=models.CharField(blank=True, editable=False, max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('staff', 'Staff'), ('teacher', 'Teacher'), ('student', 'Student'), ('terminal', 'Terminal')], default='student', max_length=20),
        ),
    ]
