# Generated by Django 5.1.15 on 2026-07-17 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_student_check_in_token_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='check_in_token',
            field=models.CharField(blank=True, max_length=64, unique=True),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['model_name', 'record_id'], name='people_audi_model_n_95b171_idx'),
        ),
    ]
