# Generated by Django 5.1.15 on 2026-07-17 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0005_alter_student_check_in_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='check_in_token',
            field=models.CharField(blank=True, editable=False, max_length=64, unique=True),
        ),
    ]
