# Generated by Django 5.1.15 on 2026-07-18 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0006_alter_student_check_in_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='contact',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='contact',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='contact',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
