# Generated by Django 5.1.15 on 2026-07-24 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0009_backfill_unique_codes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='school_code',
            field=models.CharField(blank=True, choices=[('HIS', 'HIS'), ('SPD', 'SPD'), ('SPN', 'SPN'), ('YWM', 'YWM')], default='HIS', max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='school_code',
            field=models.CharField(blank=True, choices=[('HIS', 'HIS'), ('SPD', 'SPD'), ('SPN', 'SPN'), ('YWM', 'YWM')], default='HIS', max_length=10),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='school_code',
            field=models.CharField(blank=True, choices=[('HIS', 'HIS'), ('SPD', 'SPD'), ('SPN', 'SPN'), ('YWM', 'YWM')], default='HIS', max_length=10),
        ),
    ]
