# Generated by Django 5.1.15 on 2026-08-05 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0010_alter_staff_school_code_alter_student_school_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('pending', 'Pending'), ('admin', 'Admin'), ('staff', 'Staff'), ('teacher', 'Teacher'), ('student', 'Student'), ('terminal', 'Terminal')], default='pending', max_length=20),
        ),
    ]
