# Generated by Django 5.1.15 on 2026-08-05 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0011_add_pending_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='bank_details',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='default_rate',
        ),
    ]
