# Generated by Django 5.1.15 on 2026-07-11 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education_level', models.CharField(choices=[('IAL', 'IAL'), ('IG', 'IG'), ('Year1', 'Year 1'), ('Year2', 'Year 2'), ('Year3', 'Year 3'), ('Year4', 'Year 4'), ('Year5', 'Year 5'), ('Year6', 'Year 6'), ('Year7', 'Year 7'), ('Year8', 'Year 8'), ('Year9', 'Year 9')], max_length=20)),
                ('cohort_identifier', models.CharField(max_length=1)),
                ('cohort_sub_category', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'verbose_name_plural': 'Classes',
                'unique_together': {('education_level', 'cohort_identifier', 'cohort_sub_category')},
            },
        ),
        migrations.CreateModel(
            name='TimetableSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('room', models.CharField(blank=True, max_length=100, null=True)),
                ('class_obj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timetable_slots', to='timetable.class')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_slots', to='people.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_slots', to='people.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='ClassStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_students', to='timetable.class')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_classes', to='people.student')),
            ],
            options={
                'unique_together': {('class_obj', 'student')},
            },
        ),
        migrations.CreateModel(
            name='TimetableStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_slots', to='people.student')),
                ('timetable_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_students', to='timetable.timetableslot')),
            ],
            options={
                'unique_together': {('timetable_slot', 'student')},
            },
        ),
    ]
