# Generated by Django 5.1.15 on 2026-07-13 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_auditlog'),
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='class',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='classstudent',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='timetablestudent',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='class',
            constraint=models.UniqueConstraint(fields=('education_level', 'cohort_identifier', 'cohort_sub_category'), name='unique_class_per_level_cohort'),
        ),
        migrations.AddConstraint(
            model_name='classstudent',
            constraint=models.UniqueConstraint(fields=('class_obj', 'student'), name='unique_student_per_class'),
        ),
        migrations.AddConstraint(
            model_name='timetablestudent',
            constraint=models.UniqueConstraint(fields=('timetable_slot', 'student'), name='unique_student_per_timetable_slot'),
        ),
    ]
