# Generated by Django 5.1.15 on 2026-07-17 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0005_alter_student_check_in_token_and_more'),
        ('timetable', '0002_alter_class_unique_together_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='timetableslot',
            index=models.Index(fields=['teacher', 'day_of_week'], name='timetable_t_teacher_c24da5_idx'),
        ),
    ]
