# Generated by Django 5.1.15 on 2026-07-20 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0003_timetableslot_timetable_t_teacher_c24da5_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetableslot',
            name='class_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_slots', to='timetable.class'),
        ),
        migrations.DeleteModel(
            name='TimetableStudent',
        ),
    ]
