# Generated by Django 5.1.15 on 2026-07-23 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0007_alter_staff_contact_alter_student_contact_and_more'),
        ('timetable', '0004_alter_timetableslot_class_obj_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='classstudent',
            index=models.Index(fields=['class_obj', 'student'], name='idx_class_student_rel'),
        ),
    ]
